language: cpp

env:
  global:
  - BUILD_BIOMEVAL_STATIC=ON
  - BUILD_BIOMEVAL_SHARED=ON
  - BUILD_BIOMEVAL_TESTS=ON
  - BUILD_BIOMEVAL_32BIT=OFF

jobs:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      osx_image: xcode12
      compiler: clang
    - os: osx
      osx_image: xcode11.3
      compiler: clang

addons:
   apt:
     packages:
       - libavcodec-dev
       - libavformat-dev
       - libdb++-dev
       - libhwloc-dev
       - libjpeg-dev
       - libopenjp2-7-dev
       - libopenmpi-dev
       - libpng-dev
       - libsqlite3-dev
       - libssl-dev
       - libswscale-dev
       - libtiff-dev
       - zlib1g-dev
   homebrew:
     packages:
       - berkeley-db
       - hwloc
       - jpeg-turbo
       - libpng
       - libtiff
       - openjpeg
       - openssl
       - sqlite
       - zlib

before_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_BIOMEVAL_STATIC=$BUILD_BIOMEVAL_STATIC -DBUILD_BIOMEVAL_SHARED=$BUILD_BIOMEVAL_SHARED -DBUILD_BIOMEVAL_TESTS=$BUILD_BIOMEVAL_TESTS -DBUILD_BIOMEVAL_32BIT=$BUILD_BIOMEVAL_32BIT ..

script:
    - cmake --build .
