version: 1.0.{build}

image:
  - Visual Studio 2019
  - Visual Studio 2017

configuration:
 - Release

platform:
  - x64
  - Win32

install:
- cmd: git submodule update --init
- cmd: cd C:\Tools\vcpkg
- cmd: git pull
- cmd: .\bootstrap-vcpkg.bat -disableMetrics
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- cmd: if %PLATFORM% == x64 ( vcpkg install berkeleydb hwloc libjpeg-turbo libpng openjpeg sqlite3 tiff zlib --triplet x64-windows --disable-metrics )
- cmd: if %PLATFORM% == x64 ( vcpkg install berkeleydb hwloc libjpeg-turbo libpng openjpeg sqlite3 tiff zlib --triplet x64-windows-static --disable-metrics )
- cmd: if %PLATFORM% == Win32 ( vcpkg install berkeleydb hwloc libjpeg-turbo libpng openjpeg sqlite3 tiff zlib --triplet x86-windows --disable-metrics )
- cmd: if %PLATFORM% == Win32 ( vcpkg install berkeleydb hwloc libjpeg-turbo libpng openjpeg sqlite3 tiff zlib --triplet x86-windows-static --disable-metrics )

cache: c:\Tools\vcpkg\installed\ -> appveyor.yml

before_build:
- cmd: >-
    md C:\projects\libbiomeval\install

    cd C:\projects\libbiomeval

    md build\Windows

    cd build\Windows

    cmake -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -A %PLATFORM% -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=C:\projects\libbiomeval\install C:\projects\libbiomeval

build:
  project: C:\projects\libbiomeval\build\Windows\biomeval.sln
  verbosity: normal
  parallel: true
